language: python
python:
  - "2.7"
env:
  - TOX_ENV=py27-django111
  - TOX_ENV=py37-django111
  - TOX_ENV=py37-django220

install:
  - pip install tox
notifications:
  email:
    - jason.louard.ward@gmail.com
script: tox -e $TOX_ENV
