language: python
dist: xenial
python:
  - "2.7"
env:
  - TOX_ENV=py27-django111
  - TOX_ENV=py371-django111
  - TOX_ENV=py371-django220

install:
  - pip install tox
notifications:
  email:
    - jason.louard.ward@gmail.com
script: tox -e $TOX_ENV
